# 線形代数計算

## ベクトルの記述
- 列ベクトルは成分をカンマ `,` で区切って記述する．

In [2]:
[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

- `;`や改行で区切ることもできる．

In [4]:
[1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

In [5]:
[1
 2
 3]

3-element Vector{Int64}:
 1
 2
 3

- ただし，スペースで区切ると行ベクトル（1×3行列) となってしまうので注意．

In [6]:
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

## 行列の記述
- Julia言語では，行列を扱うために `Matrix{T}` 型が用意されている．`T`は行列の成分の型を表す type parameter である．
 例えば，`Matrix{Int64}` は各成分が `Int64` 型の行列になる．
- 行列は `[...]` の内部に成分を記述して定義する．
- 成分は行ごとに並べ，セミコロン `;` で区切る．

In [7]:
[1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [8]:
# 行ごとに改行しても同じ．
[1 2 3
 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

- これは成分すべてが `Int64`型であるため，`Matrix{Int64}`型になっているが，
次のように明示的に型を指定することもできる．

In [9]:
Float64[1 2 3; 4 5 6]

2×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0

## 行列成分へのアクセス
- 変数`A`に格納した場合，第$(i,j)$成分にアクセスするには，`A[i,j]`と書けばよい．

In [10]:
A = [11 12 13; 21 22 23]

2×3 Matrix{Int64}:
 11  12  13
 21  22  23

In [11]:
A[2,1]

21

- 行列を部分的に抜き出したい場合は，例えば，`:`記号を使う．

In [12]:
A[:,3] # 第3列

2-element Vector{Int64}:
 13
 23

A[2,:] # 第2行（1×3行列ではなく，ベクトルになることに注意）

In [14]:
A[1:2,1:2] # (1,1)成分から見て2x2の部分のみを抜き出す

2×2 Matrix{Int64}:
 11  12
 21  22

## 行列の成分の書き換え
- 行列Aの$(i,j)$成分を書き換えるには，`A[i,j] = 値` と書く．

In [8]:
A = [11 12 13; 21 22 23]

2×3 Matrix{Int64}:
 11  12  13
 21  22  23

In [9]:
A[1,1] = 1
A[1,2] = 2
A[1,3] = 3

3

In [10]:
A   #確認

2×3 Matrix{Int64}:
  1   2   3
 21  22  23

- 成分をまとめて書き換えることもできる．
- 例として，Aの第2行の成分すべてを書き換えてみよう．

In [15]:
A[2,:] = [4 5 6]
A  # 確認

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

## 逆行列
正則行列 `A` の逆行列は `inv(A)` あるいは `A^-1` などで計算できる．

In [29]:
X = [1 1 1; 1 2 4; 1 3 9]

3×3 Matrix{Int64}:
 1  1  1
 1  2  4
 1  3  9

In [31]:
Y = inv(X)   # 逆行列

3×3 Matrix{Float64}:
  3.0  -3.0   1.0
 -2.5   4.0  -1.5
  0.5  -1.0   0.5

In [32]:
X*Y   # 単位行列に等しいことを確認

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

## 行列の生成
次のようなコマンドでも行列を生成できる．

|               |                       |
|:--------------|:----------------------|
|`zeros(m, n)`  | $m \times n$ のゼロ行列  |
|`ones(m, n)`   | すべての成分が `1` であるような $m \times n$ 行列 |
|`fill(a, m, n)` | すべての成分が `a` であるような $m \times n$ 行列 |
|`Array{Float64}(undef, m, n)`| 中身が初期化されていない $m \times n$ 行列 |

In [34]:
zeros(3,5)

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [35]:
ones(3,5)

3×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [36]:
fill(pi, 3, 5)

3×5 Matrix{Irrational{:π}}:
 π  π  π  π  π
 π  π  π  π  π
 π  π  π  π  π

In [37]:
Array{Float64}(undef, 3, 5)

3×5 Matrix{Float64}:
 6.91162e-310  6.91162e-310  6.91162e-310  6.91162e-310  6.91162e-310
 6.91162e-310  6.91162e-310  6.91162e-310  6.91162e-310  6.91162e-310
 6.91162e-310  6.91162e-310  6.91162e-310  6.91162e-310  6.91162e-310

### 📝 `Matrix`型と`Array`型
- 型 `T` に対して，`Matrix{T}` は `Array{T,2}` は同じ．
- 例えば，`Matrix{Int64}` は `Array{Int64, 2}` と同じ．

## 行列のサイズ取得 `size`

In [38]:
size([1 2 3; 4 5 6])     # 2x3の行列

(2, 3)

## 行列演算
- 行列 `A`, `B`の和と差は`A + B`, `A - B` で計算される．
- 積は サイズが適切であれば `A*B` で計算される． 

In [40]:
P = [1 1; 0 0] 
Q = [0 0; 1 1]

2×2 Matrix{Int64}:
 0  0
 1  1

In [41]:
P * Q     # 行列積の計算例1

2×2 Matrix{Int64}:
 1  1
 0  0

In [42]:
Q * P     # 行列積の計算例2

2×2 Matrix{Int64}:
 0  0
 1  1

In [43]:
P .* Q    # 演算子の左に dot `.` を付けると成分ごとの計算になる

2×2 Matrix{Int64}:
 0  0
 0  0

In [44]:
[1 2; 3 4].^2   # 成分ごとに2乗する

2×2 Matrix{Int64}:
 1   4
 9  16

## 転置行列
- 行列`A`の転置行列は`transepose(A)` で与えられる．
- 随伴（複素共役転置） は `adjoint(A)` or `A'`．
- これらは遅延評価であるので，実体化したい場合は`Matrix()`などを使えばよい．

In [45]:
A = [11 12 13; 21im 22im 23im]

2×3 Matrix{Complex{Int64}}:
 11+0im   12+0im   13+0im
  0+21im   0+22im   0+23im

In [46]:
transpose(A)

3×2 transpose(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 11+0im  0+21im
 12+0im  0+22im
 13+0im  0+23im

In [47]:
adjoint(A)

3×2 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 11+0im  0-21im
 12+0im  0-22im
 13+0im  0-23im

In [21]:
A'  # =adjoint(A)

3×2 adjoint(::Matrix{Complex{Int64}}) with eltype Complex{Int64}:
 11+0im  0-21im
 12+0im  0-22im
 13+0im  0-23im

In [22]:
Matrix(A') # 実体化

3×2 Matrix{Complex{Int64}}:
 11+0im  0-21im
 12+0im  0-22im
 13+0im  0-23im

## 行列の連結
- 複数の行列をブロック行列の要領で並べれば，簡単に連結することができる．

In [23]:
A = zeros(Int, 2,3)    # 見やすくするために， `Int`型にする

2×3 Matrix{Int64}:
 0  0  0
 0  0  0

In [24]:
B = ones(Int, 2,2)

2×2 Matrix{Int64}:
 1  1
 1  1

In [25]:
[A B] # 水平に連結

2×5 Matrix{Int64}:
 0  0  0  1  1
 0  0  0  1  1

In [26]:
[A B
 B A]  # 垂直方向にも連結

4×5 Matrix{Int64}:
 0  0  0  1  1
 0  0  0  1  1
 1  1  0  0  0
 1  1  0  0  0

## 内包表記による行列の生成
- 二重ループを内包表記することで行列を生成

In [48]:
M = [10i+j for i in 1:3, j in 1:5]

3×5 Matrix{Int64}:
 11  12  13  14  15
 21  22  23  24  25
 31  32  33  34  35

## 連立１次方程式の数値解法
- $n$次正方行列 $A$, $n$項列ベクトル $b$ に対して，連立一次方程式 $Ax = b$ の解は `A\b` で計算できる．

In [52]:
A = [1 2; 3 4]
b = [3, 7]
A\b

2-element Vector{Float64}:
 0.9999999999999997
 1.0000000000000002

### Warning
$b$に$A$の逆行列をかけても解が得られるが，効率が悪いので数値計算では用いられない．