# 行列計算

## 基本メソッド一覧

`A`, `B` を行列型 `Matrix` の変数とする．

|  コード    |    内容  |        
|-----------|-------------|
| `[1 2 3; 4 5 6]` | 行列の記法  |
| `Float64[1 2 3; 4 5 6]` | Float64型のMatrix  |
| `A[i,j]` | $A$の第 $(i,j)$成分 |
| `zeros(m,n)`| $m\times n$のゼロ行列 |
| `ones(m,n)` | すべての成分が1の$m\times n$行列 |
|`fill(a, m, n)` | すべての成分が `a` であるような $m \times n$ 行列 |
| `size(A)` | $A$のサイズ |
| `A + B`   | $A + B$ |
| `A - B`   | $A - B$ |
| `A*B`     | $AB$    |
| `inv(A)`  | $A^{-1}$ |
| `A^-1`    |$A^{-1}$ |
| `A\b`     | $Ax = b$の求解 |
| `A\B`     | $AX = B$の求解 |
| `[A B]`   |  列方向への連結 |
| `[A; B]`  | 行方向への連結 |
| `transpose(A)` | 転置行列 | 
| `adjoint(A)` | 随伴行列 | 
| `A'` | 随伴行列 (`adjoint(A)` と同じ) | 


以下はLinearAlgebraパッケージの読み込みが必要


|  コード    |    内容  |  
|-----------|-------------|
| `det(A)` | $A$の行列式 |
| `tr(A)` | $A$のトレース |
| `rank(A)` |$A$のランク |
| `norm(A,p)` | $A$の $p$-norm |
| `I(n)` | n次単位行列 | 
| `I` | 単位行列を表す記号．サイズは演算時に自動で設定される． |
| `eigvals(A)` | $A$の固有値 | 
| `eigvecs(A)` | $A$の固有ベクトル |


## 行列の記述
成分は行ごとに並べ，セミコロン `;` で区切る．

In [6]:
A = [11 12 13 14; 21 22 23 24; 31 32 33 34]

#= 行ごとに改行しても同じ．
[11 12 13 14;
 21 22 23 24;
 31 32 33 34]
=#

3×4 Matrix{Int64}:
 11  12  13  14
 21  22  23  24
 31  32  33  34

## 行列成分へのアクセス
行列 `A` の第$(i,j)$成分にアクセスするには，
`A[i,j]`と書けばよい．

In [8]:
@show A[1, 1] A[1, 2] A[1, 3] A[1, 4];

A[1, 1] = 11
A[1, 2] = 12
A[1, 3] = 13
A[1, 4] = 14


配列と同じように範囲を指定することで，行列を部分的に抜き出せる．

In [10]:
@show A[:, 1] # 第1列
@show A[:, 2] # 第2列
@show A[:, 3] # 第3列
@show A[:, 4]; # 第4列

A[:, 1] = [11, 21, 31]
A[:, 2] = [12, 22, 32]
A[:, 3] = [13, 23, 33]
A[:, 4] = [14, 24, 34]


In [12]:
@show A[1, :]  #第1行（1×3行列ではなく，ベクトルになることに注意）
@show A[2, :] #第2行 
@show A[3, :]; #第3行

A[1, :] = [11, 12, 13, 14]
A[2, :] = [21, 22, 23, 24]
A[3, :] = [31, 32, 33, 34]


In [14]:
A[1:3, 2:3]

3×2 Matrix{Int64}:
 12  13
 22  23
 32  33

## 行列の連結
行列を並べて書くと連結される．
例として，次の行列をいろいろな形で連結してみよう．

In [16]:
O = zeros(Int, 2, 3)    # 見やすくするために， `Int`型にする

2×3 Matrix{Int64}:
 0  0  0
 0  0  0

In [ ]:
🐕 = ones(Int, 2, 2)

2×2 Matrix{Int64}:
 1  1
 1  1

In [18]:
[O 🐕] # 水平に連結

2×5 Matrix{Int64}:
 0  0  0  1  1
 0  0  0  1  1

In [19]:
[O 🐕
    🐕 O]  # 垂直方向にも連結

4×5 Matrix{Int64}:
 0  0  0  1  1
 0  0  0  1  1
 1  1  0  0  0
 1  1  0  0  0

## 内包表記による行列の生成
各成分が定まっている行列を記述するには内包表記が役に立つ．

In [12]:
[10i + j for i in 1:3, j in 1:5]

3×5 Matrix{Int64}:
 11  12  13  14  15
 21  22  23  24  25
 31  32  33  34  35

与えられた 引数 `n` に対して，`n`次の三重対角行列を返す関数は次のように書ける．  
整数値を与えると整数型の行列になるので注意．

In [9]:
a, b = 10, -1
A(n) = [if i==j a elseif abs(i-j)==1 b else 0 end for i in 1:n, j in 1:n]

A(5) # 表示用

5×5 Matrix{Int64}:
 10  -1   0   0   0
 -1  10  -1   0   0
  0  -1  10  -1   0
  0   0  -1  10  -1
  0   0   0  -1  10

In [8]:
# Float64版
a, b = 10, -1
Float64[if i==j a elseif abs(i-j)==1 b else 0 end for i in 1:5, j in 1:5]

5×5 Matrix{Float64}:
 10.0  -1.0   0.0   0.0   0.0
 -1.0  10.0  -1.0   0.0   0.0
  0.0  -1.0  10.0  -1.0   0.0
  0.0   0.0  -1.0  10.0  -1.0
  0.0   0.0   0.0  -1.0  10.0