# 配列: [Array](https://docs.julialang.org/en/v1/manual/arrays/)
- 複数の変数や値を1列に並べて， `[...]` で囲ったものを配列という．

In [2]:
A = [1, "two" , 3, "d"]

4-element Vector{Any}:
 1
  "two"
 3
  "d"

- 配列の左から`i`番目の要素にアクセスするには，`A[i]`と書く．

In [3]:
@show A[1]
@show A[2]
@show A[3]
@show A[4]

A[1] = 1
A[2] = "two"
A[3] = 3
A[4] = "d"


"d"

- 代入も同様：

In [6]:
A[1] = "ONE"
@show A[1];    # 確認

A[1] = "ONE"


配列の先頭と末尾の要素はそれぞれ `A[begin]`, `A[end]`と書いてアクセスできる．

In [3]:
@show A[begin]
@show A[end]
@show A[end-1] # 末尾から１つ前

A[begin] = 1
A[end] = "d"
A[end - 1] = 3


3

## 配列サイズ
- 配列のサイズ（要素数）は `lendth()`で取得する

In [4]:
length(A)  

4

## コロンによる配列の抜き出し
- 例として整数の連番からなる配列を考える．

In [5]:
A = collect(1:10)     # A = [1,2, ..., 10]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

- `1:10`は1,2,...,10 という範囲を表す．
- `collect()`で範囲を配列に変換に変換する．
- 次のように書いても同じである．

In [6]:
A = Vector(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

- 配列の一部分にまとめてアクセスしたい場合は，`A[範囲]`の形で書く．

In [7]:
@show A[3:6]      
@show A[1:3:end]    # 1 から end まで 3刻み

A[3:6] = [3, 4, 5, 6]
A[1:3:end] = [1, 4, 7, 10]


4-element Vector{Int64}:
  1
  4
  7
 10

## 配列の連結
- ２つの配列`A`, `B` を連結させる場合は，`[A; B]` と書けば良い．

In [8]:
A = [1,2,3]
B = ["a", "b", "c"]
[A; B] 

6-element Vector{Any}:
 1
 2
 3
  "a"
  "b"
  "c"

- `;` は改行に相当すると解釈でき，次のように書いても同じである．

In [9]:
[A
 B]

6-element Vector{Any}:
 1
 2
 3
  "a"
  "b"
  "c"

- あるいは `vcat()` を用いてもよい．

In [10]:
vcat(A,B)

6-element Vector{Any}:
 1
 2
 3
  "a"
  "b"
  "c"

## 要素の push と pop
- 配列の末尾に要素を追加するには `push!(配列, 追加する要素)`を用いる．
- 関数名に`!`がついているのは，引数を変更する関数であることを表している．

In [11]:
A = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [12]:
push!(A, 100)

4-element Vector{Int64}:
   1
   2
   3
 100

- 配列の末尾から要素を取り出すには `pop!`を用いる．

In [13]:
pop!(A)

100

In [14]:
@show A  # 取り出したものは無くなっているはず

A = [1, 2, 3]


3-element Vector{Int64}:
 1
 2
 3

- 一部分を取り出したい場合は`splice!()`が使える．

In [15]:
A = [1,2,3,4,5]
splice!(A,2:4)   # A[2:4]を取り出す

3-element Vector{Int64}:
 2
 3
 4

In [11]:
@show A   # 取り出した部分は残っていない

A = Any["ONE", "two", 3, "d"]


4-element Vector{Any}:
  "ONE"
  "two"
 3
  "d"

## 配列に対する関数
- Juliaでは，配列を渡すと総和を返す関数 `sum()` などが予め用意されている．

In [17]:
A = [1,2,3,4,5]
@show sum(A)      # 配列の要素の総和
@show prod(A)     # 総乗
@show maximum(A)  # 最大値
@show minimum(A)  # 最小値

sum(A) = 15
prod(A) = 120
maximum(A) = 5
minimum(A) = 1


1

- 配列の中身を小さい順にソート（並べ替える）する関数も用意されている．

In [18]:
sort([5,4,3,2,1])

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [19]:
sort(["aaa", "bbb", "baa", "aab", "ab", "A"])

6-element Vector{String}:
 "A"
 "aaa"
 "aab"
 "ab"
 "baa"
 "bbb"

## dot 演算子：要素ごとの操作
- 配列`A`の要素ごとに演算，あるいは関数を作用させたい場合，
dot演算子 `.` を用いる．

In [12]:
A = [1,2,3,4,5]
@show A .+ 1     # [1+1, 2+1, 3+1, 4+1, 5+1]
@show A .^ 2     # [1^2, 2^2, 3^2, 4^2, 5^2]
@show sqrt.(A)   # [sqrt(1), sqrt(2), sqrt(3),sqrt(4),sqrt(5)]

A .+ 1 = [2, 3, 4, 5, 6]
A .^ 2 = [1, 4, 9, 16, 25]
sqrt.(A) = [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]


5-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979

## 空の配列

In [23]:
empty_array = []   # 空の配列．任意の型の変数を
vec = Float64[]    # 要素の型を指定する

Float64[]

## 配列の生成

In [25]:
zeros(3)         # `0`が3個の配列
ones(3)          # `1`が3個の配列
fill("abc", 3)  # "abc"が3個の配列

3-element Vector{String}:
 "abc"
 "abc"
 "abc"

#### 📝 配列の参照とコピー：`deepcopy`
- Julia言語では，配列のコピーは **参照コピー**である．
- つまり，配列の要素が記録されているメモリアドレスのコピーになる．
- 次の例を見れば参照がどういうものかわかると思う．

In [26]:
a = [1,2,3]
b = a     # 参照のコピー
a[1] = 100   
@show a, b;  # aを変えるとbも変わる

(a, b) = ([100, 2, 3], [100, 2, 3])


In [27]:
b[2] = -123 
@show a, b;  # bを変えるとaも変わる

(a, b) = ([100, -123, 3], [100, -123, 3])


- `a`, `b` のメモリアドレスを表示する．両者は一致しているはずである．

In [28]:
@show pointer(a)
@show pointer(b)

pointer(a) = Ptr{Int64} @0x00007f6b107a60b0
pointer(b) = Ptr{Int64} @0x00007f6b107a60b0


Ptr{Int64} @0x00007f6b107a60b0

- 配列を値ごと複製してコピーするには `deepcopy()`を用いる．

In [29]:
a = [1,2,3]    # 再定義
c = deepcopy(a)     # 配列そのものを複製
a[1] = 100   # cは書き換わらない 
@show a, c;  

(a, c) = ([100, 2, 3], [1, 2, 3])


In [30]:
c[2] = 200 　# aは書き換わらない
@show a, c;  

(a, c) = ([100, 2, 3], [1, 200, 3])


- `deepcopy()`で `c` は `a` とは異なるメモリアドレスにデータが複製されている．

In [31]:
@show pointer(a)
@show pointer(c)

pointer(a) = Ptr{Int64} @0x00007f6afa9be580
pointer(c) = Ptr{Int64} @0x00007f6afa7fc9f0


Ptr{Int64} @0x00007f6afa7fc9f0

<img src="deepcopy.png">

#### Warning
- `deepcopy()`は配列がそのまま複製されるので，コピーするのに時間もかかるし，新たにメモリも確保されるので注意．

In [32]:
a = [1,2,3]
@time b = a    # アロケーション（割当）は行われない
@time c = deepcopy(a)   # アロケーションされる 

  0.000000 seconds
  0.000002 seconds (3 allocations: 480 bytes)


3-element Vector{Int64}:
 1
 2
 3

## 📝 浅いコピーと深いコピー
- 配列をコピーする関数には，
    - `deepcopy()` : **深いコピー (deepcopy)** 
    - `copy()`:  **浅いコピー(shallow copy)**
の2種類がある．

- `deepcopy()`は配列に格納された値をすべてそのままコピーして新しい配列を生成する．
- これに対して，`copy()`は は各要素の**参照**をコピーする．
- 両者の違いは，配列の中に配列が含まれる場合に明確に現れる．
- まずは 深いコピーの挙動を見る．

In [33]:
a = [1,2,[3,4]]
deep_a = deepcopy(a)
a[1] = 100    # 1 を 100に
a[3][1] = 300   # [3,4] を [300, 4] に
@show a
@show deep_a;   # deep_a は何も変わっていない

a = Any[100, 2, [300, 4]]
deep_a = Any[1, 2, [3, 4]]


- 次に浅いコピーの場合：

In [34]:
a = [1,2,[3,4]]
shallow_a = copy(a)     # 浅いコピー
a[1] = 100    # 1 → 100に
a[3][1] = 300   # [3,4] → [300, 4] に
@show a
@show shallow_a;   # shallow_a[1]は変わっていないが，shallow_a[3]は変わっている

a = Any[100, 2, [300, 4]]
shallow_a = Any[1, 2, [300, 4]]


- 深いコピー`deepcopy(a)`の場合，`a` に配列が含まれている場合，その配列の中身も丸ごとコピーされて，
`b = [値, 値, [値, 値]]` となる．

- 浅いコピー`copy(a)` の場合，`a`内の配列は参照がコピーされる：`b = [値，値，参照]` ．
この結果，`b[3]`は `a[3] = [3,4]` への参照となる．

#### 📝 `配列=配列`の挙動
- Julia言語やC/C++, Pythonでは，`配列=配列`は参照コピーになる．
- 一方で，FortranやMATLABでは値コピーになるので，注意が必要である．
- 値コピーの方がコードの挙動がわかりやすいが，無頓着に書きならべると無駄なアロケーションを発生させてしまう可能性がある．