# 配列と数ベクトル
## 配列 [Array](https://docs.julialang.org/en/v1/manual/arrays/)
次のようにオブジェクトが一列に並んでいるデータを配列という．

In [7]:
A = [1, "II", "tri", "four"]

4-element Vector{Any}:
 1
  "II"
  "tri"
  "four"

配列の先頭（左）から`i`番目の要素にアクセスするには，`A[i]`と書く．

In [8]:
@show A[1] A[2] A[3] A[4];

A[1] = 1
A[2] = "II"
A[3] = "tri"
A[4] = "four"


番号でなくとも，先頭は`begin`，末尾は`end` でもアクセスできる．

In [10]:
A[begin] = "書き換え"
@show A

A = Any["書き換え", "II", "tri", "four"]


4-element Vector{Any}:
 "書き換え"
 "II"
 "tri"
 "four"

## コロンによる配列の抜き出し
例として整数の連番からなる配列を考える．

In [13]:
# `collect()` はインデックスを配列に変換する関数
A = collect(1:9)


9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

`1:10`は　1,2,...,10 というインデックスを表す．  

配列の一部分にまとめてアクセスしたい場合は，`A[インデックス]`の形で書く．
例えば，

In [14]:
A[3:7]

5-element Vector{Int64}:
 3
 4
 5
 6
 7

In [16]:
A[1:3] = [100, 200, 300];
@show A

A = [100, 200, 300, 4, 5, 6, 7, 8, 9]


9-element Vector{Int64}:
 100
 200
 300
   4
   5
   6
   7
   8
   9

![array](array.svg)

## 配列に関する基本メソッド
`A`を配列とする．

| コード|  内容 |
|------|------|
| `A[i]` | `i`番目の要素 |
| `A[1]` | 先頭の要素 |
| `A[begin]` | 先頭の要素 |
| `A[end]` | 末尾の要素 | 
| `length(A)` | 配列の要素数 |
| `sum(A)` | `A`の要素の総和 | 
|`prod(A)` | `A`の要素の総乗 | 
| `maximum(A)` | `A`の要素の最大値 | 
| `minimum(A)` | `A`の要素の最小値 |
| `sort(A)` | `A` を降順に並べ替える |
| `zeros(n)` | `n`個のゼロからなる配列を生成 |
| `ones(n)` | `n`個の`1`からなる配列を生成 |
| `fill(n,x)` | `n`個の`x`からなる配列を生成 |



## dot 演算子
配列`A`の要素ごとに演算，あるいは関数を作用させたい場合，
dot演算子 `.` を用いる．

In [11]:
A = [1, 2, 3, 4, 5]
@show A .^ 2     # [1^2, 2^2, 3^2, 4^2, 5^2]
@show sqrt.(A);   # [sqrt(1), sqrt(2), sqrt(3),sqrt(4),sqrt(5)]

A .^ 2 = [1, 4, 9, 16, 25]
sqrt.(A) = [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]


## 内包表記 (Comprehensions)
ブラケット `[ ... ]` の内部に `for` ループを記述することで配列を生成できる．

In [14]:
A = [i^2 for i in 1:5]  # =[1^2, 2^2, 3^2, 4^2, 5^2]

5-element Vector{Int64}:
  1
  4
  9
 16
 25