# 配列と数ベクトル
## 配列 [Array](https://docs.julialang.org/en/v1/manual/arrays/)
オブジェクトを並べて  `[...]` で囲ったものを配列という．

In [27]:
A = [1, "II" , "tri", "four"]

4-element Vector{Any}:
 1
  "II"
  "tri"
  "four"

配列の先頭（左）から`i`番目の要素にアクセスするには，`A[i]`と書く．

In [28]:
@show A[1] A[2] A[3] A[4];

A[1] = 1
A[2] = "II"
A[3] = "tri"
A[4] = "four"



## 配列サイズ
配列のサイズ（要素数）は `lendth()`で取得する

In [ ]:
length(A)  

10

## 数ベクトル
数ベクトルは，要素が数値の配列として扱うことができる．

In [45]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [ ]:
v = [1,0,0]
w = [0,1,0]
@show v + w


v + w = [1, 1, 0]


3-element Vector{Int64}:
 1
 1
 0

In [ ]:
using LinearAlgebra
a = [1,0,0]
b = [0,1,0]
c = [0,0,1]
d = [1,1,1]

## コロンによる配列の抜き出し
例として整数の連番からなる配列を考える．

In [ ]:
B = collect(1:10)     # B = [1,2, ..., 10]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

`1:10`は1,2,...,10 という範囲を表す．  
`collect()`で範囲が配列に変換されたということである．

配列の一部分にまとめてアクセスしたい場合は，`A[範囲]`の形で書く．

## 配列に対する関数
Juliaでは，配列を渡すと総和を返す関数 `sum()` などが予め用意されている．

In [16]:
A = [1,2,3,4,5]
@show sum(A)      # 配列の要素の総和
@show prod(A)     # 総乗
@show maximum(A)  # 最大値
@show minimum(A);  # 最小値

sum(A) = 15
prod(A) = 120
maximum(A) = 5
minimum(A) = 1


配列の中身を小さい順にソート（並べ替える）する関数も用意されている．

In [18]:
sort([5,4,3,2,1])

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [19]:
sort(["aaa", "bbb", "baa", "aab", "ab", "A"])

6-element Vector{String}:
 "A"
 "aaa"
 "aab"
 "ab"
 "baa"
 "bbb"

## dot 演算子：要素ごとの操作
配列`A`の要素ごとに演算，あるいは関数を作用させたい場合，
dot演算子 `.` を用いる．

In [19]:
A = [1,2,3,4,5]
@show A .^ 2     # [1^2, 2^2, 3^2, 4^2, 5^2]
@show sqrt.(A);   # [sqrt(1), sqrt(2), sqrt(3),sqrt(4),sqrt(5)]

A .^ 2 = [1, 4, 9, 16, 25]
sqrt.(A) = [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]


## 空の配列

In [23]:
empty_array = []   # 空の配列．任意の型の変数を
vec = Float64[]    # 要素の型を指定する

Float64[]

## 配列の生成

In [21]:
@show zeros(3)         # `0`が3個の配列
@show ones(3)          # `1`が3個の配列
@show fill("abc", 3)  # "abc"が3個の配列
;

zeros(3) = [0.0, 0.0, 0.0]
ones(3) = [1.0, 1.0, 1.0]
fill("abc", 3) = ["abc", "abc", "abc"]


## 内包表記 (Comprehensions)
ブラケット `[ ... ]` の内部に `for` ループを記述することで配列を生成できる．

In [ ]:
A = [i^2 for i in 1:5]  # =[1^2, 2^2, 3^2, 4^2, 5^2]

5-element Vector{Int64}:
  1
  4
  9
 16
 25