# 配列と数ベクトル
## 配列 [Array](https://docs.julialang.org/en/v1/manual/arrays/)
次のようにオブジェクトが一列に並んでいるデータのことを配列という．

In [1]:
X = [1, "II", "tri", "four"]

4-element Vector{Any}:
 1
  "II"
  "tri"
  "four"

配列の先頭（左）から`i`番目の要素にアクセスするには，`X[i]`と書く．

In [2]:
@show X[1] X[2] X[3] X[4];

X[1] = 1
X[2] = "II"
X[3] = "tri"
X[4] = "four"


番号でなくとも，先頭は`begin`，末尾は`end` を使用してアクセスできる．

配列の先頭要素を書き換えてみよう．

In [3]:
X[begin] = "壱"
@show X

X = Any["壱", "II", "tri", "four"]


4-element Vector{Any}:
 "壱"
 "II"
 "tri"
 "four"

## 範囲 (range) による配列アクセス
例として，連続する整数からなる配列を考える．

In [4]:
# 1:9 は 1 から 9 までの整数の範囲を表す
# `collect()` は範囲を配列に変換する関数
A = collect(1:9)


9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

配列の一部分にまとめてアクセスしたい場合は，`A[範囲]`の形で書く．
例えば，

In [5]:
A[3:7]

5-element Vector{Int64}:
 3
 4
 5
 6
 7

特定の範囲に代入することも可能．

In [6]:
A[1:3] = [100, 200, 300];
@show A

A = [100, 200, 300, 4, 5, 6, 7, 8, 9]


9-element Vector{Int64}:
 100
 200
 300
   4
   5
   6
   7
   8
   9

![array](array.svg)

## 配列に関する基本メソッド
`A`を配列とする．

| コード|  内容 |
|------|------|
| `A[i]` | `i`番目の要素 |
| `A[1]` | 先頭の要素 |
| `A[begin]` | 先頭の要素 |
| `A[end]` | 末尾の要素 | 
| `length(A)` | 配列の要素数 |
| `sum(A)` | `A`の要素の総和 | 
|`prod(A)` | `A`の要素の総乗 | 
| `maximum(A)` | `A`の要素の最大値 | 
| `minimum(A)` | `A`の要素の最小値 |
| `sort(A)` | `A` を降順に並べ替える |
| `zeros(n)` | `n`個のゼロからなる配列を生成 |
| `ones(n)` | `n`個の`1`からなる配列を生成 |
| `fill(n,x)` | `n`個の`x`からなる配列を生成 |



## dot 演算子
演算子や関数を，配列`A`の要素ごとに作用させたい場合，
dot演算子 `.` を用いる．

In [7]:
A = [1, 2, 3, 4, 5]
@show A .^ 2     # [1^2, 2^2, 3^2, 4^2, 5^2]
@show sqrt.(A);   # [sqrt(1), sqrt(2), sqrt(3),sqrt(4),sqrt(5)]

A .^ 2 = [1, 4, 9, 16, 25]
sqrt.(A) = [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]


## 内包表記 [Comprehensions](https://docs.julialang.org/en/v1/manual/arrays/#man-comprehensions)
ブラケット `[ ... ]` の内部に `for` ループを記述することで配列を生成する記述方法を内包表記という．

In [8]:
[i^2 for i in 1:5]  # =[1^2, 2^2, 3^2, 4^2, 5^2]

5-element Vector{Int64}:
  1
  4
  9
 16
 25

for文のあとにif文を追加することで，条件を満たすものだけ抽出することができる．

In [9]:
[i for i in 1:10 if i % 2 == 0]  # 偶数の配列

5-element Vector{Int64}:
  2
  4
  6
  8
 10

ちなみに範囲を使って次のように書くこともできる．

In [10]:
collect(2:2:10)  # 2 から 10 までの範囲で 2 ずつ増加する．真ん中の2が増分を表す．

5-element Vector{Int64}:
  2
  4
  6
  8
 10

## 内包表記に関するTips

$1+2+\cdots+99+100 = 5050$ を計算するには，
 `sum()`関数を用いて，次を実行すればよい．

In [11]:
@time sum(i for i in 1:100)

  0.000000 seconds


5050

`@time` は実行時間とメモリアロケーション（割り当て）を表示するマクロである．    
経過時間は 0[s] と表示されているのは，実行が一瞬で終わり，計測精度を超えたためと思われる．  
経過時間以外に何もされていないのは，メモリの確保が行われなかったことを表している．

以下のように `[...]` で囲って書いても同じ結果が得られるが，配列が生成される分だけ効率が悪い．


In [12]:
@time sum([i for i in 1:100])

  0.000007 seconds (2 allocations: 928 bytes)


5050

`2 allocations: 928 bytes`  は メモリ確保が2回行われ，その総容量が928バイトであることを示している．